### ISSUE TITLE
Monitor select

### ISSUE THREAD

**Issue by paum3** [phenax/bsp-layout#11]
Hi, thank you for all this effort.
I assume, it is possible to add a monitor choice not only desktop.
How could one achieve this ?
thank you

paum

**Comment by phenax** [comment]
@paum3, There is no way currently in the script to set a layout specific to a monitor.
I think you should set the layout on the desktops that you configure to be on the monitor. If your use-case is to only do that when a monitor exists, you could use the output of `xrandr --listmonitors` to check if your monitor is connected and set the layouts accordingly.

Example: If you keep 8, 9, 10 on your second monitor
```
set_tall_layout() {
  while [[ $# != 0 ]]; do
    bsp-layout set tall $1;
    shift 1;
  done;
}

set_tall_layout 8 9 10;
```

With monitor check,
```
if (xrandr --listmonitors | grep HDMI1); then
  set_tall_layout 8 9 10;
fi;
```

**Comment by paum3** [comment]
@phenax , Thank you for your suggestion. I have a strange behaviour. It depends whenever I am changing layout on my current focused desktop or not. 
If on focused, the choosen layout changes immediately. If I am changing layout on the other desktop I am currently in, the change takes effect only, if I go to the desired desktop and add a new window manually - in this moment the windows are rearranging.

Is it only on my machine due some options ?
I am on archlinux box.

Thank you.

**Comment by phenax** [comment]
Yes. That is currently how it works. So the layout scripts re-arrange the current desktop and the process that manages the layout, decides whether it needs to be re-arranged or not. This was just the simpler way to do it.
If you are having any issues with the current behavior, you should create an issue. I'll try to spend some time on it.

**Comment by paum3** [comment]
Thank your @phenax for fast response. I don't want to waste your time, but it will be really good for my situation for me, if it could behave like like that, so I am filling an issue and you will see if you will have time. Thank you anyway.

**Comment by phenax** [comment]
No problem buddy. Im closing this issue.
