### ISSUE TITLE
Re-arranging (not current) desktop

### ISSUE THREAD

**Issue by paum3** [phenax/bsp-layout#12]
I would love, if bsp-layout could re-arrange not only current focused desktop.

Current behaviour is, that if I change layout on other than focused desktop, the new layout is applying only, if I focus to this desktop and create a new window there.

thank you

**Comment by PoSayDone** [comment]
Any news?

**Comment by PoSayDone** [comment]
Found ultra tricky hack. I'm absolutely sure that is very stupid, but it works.
Just add your layout command in sxhkd:
```
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'; \
  	bsp-layout set tall 3 -- --master-size 0.75
```

**Comment by phenax** [comment]
I haven't been able to make time for this yet. But I have a solution for it, similar to the one @PoSayDone mentioned with sxhkd. The idea is to subscribe to `desktop_focus` and re-running the layout. If anyone wants to pick this up, feel free otherwise I'll do it myself when I get some free time.

**Comment by a2n-s** [comment]
Hi @paum3 and @PoSayDone :wave: 

this issue hasn't died!

i'll investigate #32 and come back to you shortly :yum:
