### ISSUE TITLE
How To Cycle Through List Of Layouts?

### ISSUE THREAD

**Issue by rjhilgefort** [phenax/bsp-layout#13]
I'm looking to do something similar to `bspc desktop -l next`, but with the layouts that this package provides. Is this possible?

**Comment by rjhilgefort** [comment]
Sorry for the beginner question, I'm new to `bspwm`/`sxhkd` and still learning some of the tricks, I got this figured out like this if anyone is curious:

```
# Cycle through layouts
super + d
  bsp-layout set {tall,rtall,wide,rwide,even,tiled}
```

**Comment by phenax** [comment]
Thank you for creating this issue. Glad to see you found a workaround for it. I have implemented this feature in a pr now. After some testing it will be available in master and the aur.

**Comment by rjhilgefort** [comment]
Great! Thanks!

**Comment by phenax** [comment]
This  feature has been merged to master. Feel free to test it out. Not available in aur yet.

**Comment by rjhilgefort** [comment]
Nice, thanks!
