### ISSUE TITLE
Set the master size for layouts in `bsp-layout once`

### ISSUE THREAD

**Issue by rsmith31415** [phenax/bsp-layout#15]
HI @phenax,

Excellent project :-) 

I found that it is not currently possible to set the master size for `bsp-layout once`. For example, the following command ignores `--master-size`: 

```
bsp-layout once tall -- --master-size 0.3
```

Here you can see an example of this behavior. In the first part of this demo, `bsp-layout set tall -- --master-size 0.3` is executed (which works correctly) and then successive values of master-size for `bsp-layout once tall -- --master-size` are ignored.

![screencast-master-size](https://user-images.githubusercontent.com/599274/99623461-cd1cb580-29f1-11eb-9be9-598bc6c6418d.gif)

I'm running bspwm 0.9.10-9-g853bb73 and bsp-layout 0.0.3

Thanks!

**Comment by phenax** [comment]
Thank you for reporting this! I've fixed this bug in master. Can you test it out?

**Comment by rsmith31415** [comment]
I can confirm this issue has been fixed. Thank you!
