### ISSUE TITLE
Inconsistencies when changing layouts

### ISSUE THREAD

**Issue by rsmith31415** [phenax/bsp-layout#16]
Hi @phenax 

I noticed small inconsistencies when moving from one layout to the next. 

In the following screencast, `bsp-layout once wide` runs as usual, but then changing the layout to `rtall` leads to unexpected results and finally, running `bsp-layout once rtall`again fixes the layout.

![screencast-changing-layouts](https://user-images.githubusercontent.com/599274/99624986-d8bdab80-29f4-11eb-9658-4beedd83df9f.gif)

I'm running bspwm 0.9.10-9-g853bb73 and bsp-layout 0.0.3

Thanks!

**Comment by phenax** [comment]
This bug has been fixed in master. Let me know if the issue persists.

**Comment by rsmith31415** [comment]
I believe this issue has been fixed when cycling through layouts using `bsp-layout set`, but it hasn't been fixed with `bsp-layout once`. Can you confirm that the issue persists after executing `bsp-layout once wide -- --master-size 0.5` and then `bsp-layout once rtall -- --master-size 0.5`?

Thanks!

**Comment by phenax** [comment]
@phenax, I've pushed a change. Can you verify?

**Comment by rsmith31415** [comment]
It is has been fixed now :+1: 

Thank you!
