### ISSUE TITLE
Conflict with option `automatic_scheme longest_side` triggers a loop

### ISSUE THREAD

**Issue by rsmith31415** [phenax/bsp-layout#19]
Hi again @phenax 

I upgraded to the latest version 0.0.4 and found a conflict when the option `bspc config automatic_scheme longest_side` (which is the default) is changed to `bspc config automatic_scheme spiral`.

In the following screencast, you can see a loop in the layouts only after changing to `automatic_scheme spiral`. It doesn't really matter the initial polarity (e.g. `bspc config initial_polarity second_child`)

![screencast-automatic-scheme-conflict](https://user-images.githubusercontent.com/599274/99736173-8e3b3e00-2a8b-11eb-9ea9-84e842ec1b74.gif)

Regards

**Comment by phenax** [comment]
Thank you for reporting this. Seems like bspwm is doing something weird for the spiral scheme. The `grid` layout branch ( #17 ) fixes the infinite loop issue but the 3rd node gets placed incorrectly. It gets corrected on adding or removing a node. I'll try to debug it.

**Comment by phenax** [comment]
I've fixed the issue in the grid branch by temporarily setting the automatic_scheme to `alternate` while applying the layout and then resetting it afterwards. You can test it out and let me know.

**Comment by rsmith31415** [comment]
Hi @phenax 

Not sure if there is something wrong with the installation, but I still get more or less the same kind of loop. I switched to the branch `feature/grid` and then ran `sudo ./install.sh`. I also confirmed that `/src` contains your recent changes, but this is the current behavior:

![screencast-automatic-scheme-conflict_2](https://user-images.githubusercontent.com/599274/99788310-907eb600-2ae6-11eb-8f97-5f590103ac46.gif)

You can see the options set in the first terminal (mainly, `automatic_scheme spiral` and `initial_polarity second_child`)

Let me know if I'm missing something here.

Thanks!

**Comment by phenax** [comment]
You'll have to run `sudo ./install.sh local` for installing from a cloned repo

**Comment by rsmith31415** [comment]
I just tested in a couple of environments and works perfectly! :+1: 

By the way, I noticed the layout is not correct when there are floating nodes, but I think that is a completely different issue, right?

**Comment by phenax** [comment]
Yes. Floating windows are a bit of a pain to handle. If you can create an issue describing the case where it breaks, I'd really appretiate it!
