### ISSUE TITLE
Add grid layout

### ISSUE THREAD

**Issue by phenax** [phenax/bsp-layout#2]
```
________________
|____|____|____|
|____|____|____|
|____|____|____|
|____|____|____|

________________
|____|____|____|
|____|____|____|
|____|____|____|
|_______|______|

________________
|____|____|____|
|____|____|____|
|____|____|____|
|______________|

```

**Comment by rjhilgefort** [comment]
I would really love to see this. I know we have `even`, but in my experience, it doesn't change anything from the normal `tile` layout. Is there anything I can do to help? (I'm pretty new to bspwm, but I'm happy to give some time if it would be of use)

**Comment by phenax** [comment]
@rjhilgefort currently Im unable to make time for this but let me know if you want to give this a shot.

**Comment by rjhilgefort** [comment]
I'd like to give it a shot, but I'm afraid I'm still a little too new to `bspwm`. I'll poke around the source code here though and see if I can find some inspiration or leads on what to do to solve this.

Alternatively, I did find a solution elsewhere that mostly works (sometimes doesn't balance in a grid, but does about 90% of the times). If you think this solution is on the right path, I can look to PR it to this project. Here's a link to the comment, but I'll also drop the script/command here as well.

https://github.com/baskerville/bspwm/issues/900#issuecomment-477830957

```sh
#!/bin/sh

target=first
# the sort is just for consistency
for node in $(bspc query -N -n .local.window | sort); do
  bspc node $node -n "$(bspc query -N -n @$(bspc query -D -d):/${target})"
  [ "$target" = "first" ] && target="second" || target="first"
done
bspc node @/ -B
```

**Comment by phenax** [comment]
That looks good. You can try it out by placing it in the `src/layouts` directory. To install the changes, run `sudo ./install.sh local`.

**Comment by phenax** [comment]
I've created a pr for grid layout with the solution you linked me to. It seems to be too buggy to push righ away tho. I'll work on it some more and let you know. In the meanwhile, you can checkout that branch and test it out.

**Comment by rjhilgefort** [comment]
awesome! I had it on my todo list to do this weekend, I'll check out your branch and try it out. Thanks!
