### ISSUE TITLE
Latest install fails on Arch: `bsp-layout not found`

### ISSUE THREAD

**Issue by rjhilgefort** [phenax/bsp-layout#21]
Since the latest release, it seems that I can't install `bsp-layout` any longer or use it. Something I'm doing wrong?

![image](https://user-images.githubusercontent.com/2034823/99889700-ee112080-2c14-11eb-87a2-6a71bb1239f8.png)

**Comment by rjhilgefort** [comment]
I tried to remove it and then install again, same result.

**Comment by phenax** [comment]
Can you try clearing the package cache? If you know where `pacmac` stores its cache (Try `~/.cache/pacman`), I'd suggest looking for `bsp-layout` and removing it. Alternatively, `pamac clean` will clean all cached packages.

**Comment by rjhilgefort** [comment]
I ran `pamac clean` and then tried to reinstall- same result.

**Comment by cheerio-pixel** [comment]
Got the same problem

**Comment by phenax** [comment]
I've added a `bsp-layout-git` package to AUR which should work for now. I'm not entirely sure about the whats causing this issue as the installation script works. Even `makepkg -si` on the `aur` branch would install the package correctly but installing it through a package manager doesn't. I'll work on this and update this issue soon.

**Comment by rjhilgefort** [comment]
@phenax thank you and thanks for the upkeep on this package!

**Comment by cheerio-pixel** [comment]
What's the difference between one and another, because it didn'd work for me but building from `./install.sh`did. I think you are correct, the problem is with the aur helper.

**Comment by phenax** [comment]
`bsp-layout` package installs the last release. `bsp-layout-git` installs the master branch via the curl command in the readme. I'll look into the problem when I get the time. I'd suggest when this issue is resolved, you use the `bsp-layout` package as that would be more stable.

**Comment by phenax** [comment]
@cheerio-pixel, @rjhilgefort. I published version 0.0.5 for `bsp-layout`. Can you verify if the issue is resolved?

**Comment by cheerio-pixel** [comment]
I doubted for like 10 minutes; but yes, it works.

**Comment by rjhilgefort** [comment]
Works for me!
