### ISSUE TITLE
Using Makefile instead of install script

### ISSUE THREAD

**Issue by FollieHiyuki** [phenax/bsp-layout#23]
This will make it easier for a packager (and users) to control how things go into the system (through flags), instead of accepting the hard coded settings (man page path, binary path, ...).

**Comment by phenax** [comment]
I agree. I've had this on my mind for some time. I'll work on this.

**Comment by FollieHiyuki** [comment]
Thanks for the quick response. I see you made the Makefile. Here is my preference, correct me if I'm wrong:
- Using `/usr/local` as the default PREFIX is probably preferable
- We can use `cp -rf` and `ln -sf` so that doing an uninstall before installing is not needed
- `chmod 755` is better than `chmod +x` (though they do the same thing here)
- Small typo: `echo "Unstalled bsp-layout"`

**Comment by phenax** [comment]
Thanks a lot for the suggestions! I'll add that in.
Currently the aur package is still using the `install.sh` script which internally uses the makefile. This is because I need to sort out the source import path inside the scripts first. I'll close this issue once that is done.

**Comment by FollieHiyuki** [comment]
Please ping me and make a release when you are done with it. I'll be happy to package this for Void Linux.

**Comment by phenax** [comment]
@FollieHiyuki, applied your suggestions. I've released 0.0.8 on github (Will create an AUR release tomorrow). The makefile now works with alternate prefixes.

**Comment by FollieHiyuki** [comment]
Nice. I think we can close this issue.

Looks good now.

**Comment by FollieHiyuki** [comment]
Hi again @phenax . I only noticed some problems when trying to package this. Can you fix the makefile?

> VERSION = 0.0.5

Update the version here?

> MAN_PATH = ${DESTDIR}${MANPREFIX}/man1
> ...
> MANPAGE = ${DESTDIR}${MAN_PATH}/bsp-layout.1

The ${DESTDIR} is redundant here, which leads to problem when packaging using a fake $DESTDIR path.

And also can you bump to version 0.0.9 or something after fixing? That would be nice.

**Comment by phenax** [comment]
Oops. My bad. I've released `0.0.9`

**Comment by FollieHiyuki** [comment]
You still forgot to bump the version in the makefile :) 
It doesn't affect anything so no need to fix immediately. It builds correctly now, thanks for fast response
