### ISSUE TITLE
Fail to install with curl install script

### ISSUE THREAD

**Issue by AnoRebel** [phenax/bsp-layout#24]
I'm on the latest Linux Mint version with `zsh` as my default shell.
I tried installing via the curl `install.sh` script but found that it fails due to syntax issues.
Since the script is piping to `sh`, and it seems(atleast in my system), `sh` doesnt support some bash syntax.

For a fix I changed the `sh` to `bash` and everything went. 
I'm not sure if it's still relevant now as the new installation method fixes it altogether but I figured it wouldnt hurt for anyone else who would use it and get the error.

**Comment by phenax** [comment]
Thanks for letting me know! I've updated the readme
