### ISSUE TITLE
Master window size %?

### ISSUE THREAD

**Issue by tamis-laan** [phenax/bsp-layout#3]
Is it possible to set the default size of the master window? Now the master window is just 50% of the space, I would like it to be something lime 65%.
I'm using `bsp-layout set wide I` and `bsp-layout set tall II`.

**Comment by phenax** [comment]
You can configure the layout ratio in a `~/.config/bsp-layout/layoutrc` file.
You can find an example for this in this repos `example.layoutrc`

```bash
cp example.layoutrc ~/.config/bsp-layout/layoutrc;
```

Thank you @tamis-laan for pointing this out. I'll add document this in the README soon

**Comment by tamis-laan** [comment]
nice! I wil take a look, however is it not a bit overkill to have a rc file? Why not add it to the command it self? I use those commands in my bspwmrc file and it would be nicer to keep al my configurations in that file.

**Comment by phenax** [comment]
Makes sense. Initially I was avoiding having any complications with maintaining cli arguments for internal stuff. But this does seem like a case for command line arguments.

**Comment by phenax** [comment]
Closing this issue. I have opened a new issue for cli arguments #4

**Comment by phenax** [comment]
@tamis-laan This feature has been implemented in master.

```bash
// Currently focused workspace
bsp-layout set tall -- --master-size 0.4

// Workspace 6
bsp-layout set tall 6 -- --master-size 0.4
```
