### ISSUE TITLE
Replace "bsp-layout cycle" with "bsp-layout {next,prev}"?

### ISSUE THREAD

**Issue by hamensman** [phenax/bsp-layout#40]
I think the `cycle` parameter should be replace with `next` and `prev` - much like in other default commands.

So I could do something like:
```bash
super + {p,o}
bsp-layout {next,prev}
```
Really, `bsp-layout next` would do the same thing as the existing `bsp-layout cycle`, but with the added option of going **back** a layout with `bsp-layout prev`.

If this feature already exists, feel free to close this issue.

**Comment by phenax** [comment]
Fixed in #41
