### ISSUE TITLE
Add templates for bug reports and feature requests

### ISSUE THREAD

**Issue by a2n-s** [phenax/bsp-layout#51]
I would like to add templates when opening issues, mainly for two reasons:
- help people write issues easily
- auto-label the issues

i think we could get inspiration from the issue tracker of [doomemacs/doomemacs](https://github.com/doomemacs/doomemacs) which is very cool! 
ours would be greatly simplified to fit the needs of `bsp-layout` :yum: 
- i think the sections and the required ones are sensible and, with the text areas, it is very easy to fill in :+1: 
- obviously, the comments can be removed and only the titles and the boxes are really usefull, with maybe some of the comments

finally, i thought about auto-labelling as follows:
- `enhancement` and `needs-triage` for the feature requests
- `unverified` and `needs-triage` for the bug reports

what are your thoughts about that @phenax? :blush: 
you can see what it could look like on [the issue tracker of doomemacs](https://github.com/doomemacs/doomemacs/issues/new/choose) and, if that's ok, i could show you, here or in a PR directly, a greatly simplified version of this :wink:

**Comment by phenax** [comment]
Sounds good. We get started with a basic template.

**Comment by a2n-s** [comment]
> Sounds good. We get started with a basic template.
>
cool :yum: 

will propose a first version of that soon :+1:
