### ISSUE TITLE
Remove the `;` at the end of the lines (just a question)

### ISSUE THREAD

**Issue by zakariaGatter** [phenax/bsp-layout#64]
i used `bsp-layout` and i love it 

after checking the source code i find out that you use `;` at the end of the line 

But bash don't need it. So i want to ask you to create a `pull request` to improve the script 

thank you again

**Comment by amtoine** [comment]
hi @zakariaGatter :wave: 

> i used `bsp-layout` and i love it
>
glad you like the project :relieved: :star_struck: 

> after checking the source code i find out that you use `;` at the end of the line
>
you are right on that :thinking: 
and there might be lines missing the `;` at the end too... :confused: 

just being curious, is there a rule or a standard pushing people not to use `;` at the end of the lines? :yum: 

> So i want to ask you to create a pull request to improve the script
>
i can submit something for sure and see if @phenax is up with merging that in the code base :wink:

**Comment by zakariaGatter** [comment]
> just being curious, is there a rule or a standard pushing people not to use ; at the end of the lines? 😋

no there is no standerd just to make script look clean and not confuse newcomers

Also `;` only used if you want to Execute Two Commands in the same line so add it at the end is pointless

if you want i can do the changes and made a `pull request` and if not satisfied we can ignore it

**Comment by amtoine** [comment]
> no there is no standerd just to make script look clean and not confuse newcomers
> 
looks sensible to me :ok_hand: 

> Also `;` only used if you want to Execute Two Commands in the same line so add it at the end is pointless
> 
> if you want i can do the changes and made a `pull request` and if not satisfied we can ignore it
>
i'm almost done with it, do not worry with that :wink:

**Comment by amtoine** [comment]
And there it is :wink: 

do not hesitate to point out `;` i could have missed :+1:

**Comment by zakariaGatter** [comment]
what you did is wanderful everything look good and clean 👍🏻
