### ISSUE TITLE
Add output in terminal for all layout changes

### ISSUE THREAD

**Issue by datsfilipe** [phenax/bsp-layout#67]
### Describe your request

Currently, when switching between all available layouts, some of the operations shows the change information in terminal output, such as "tiled:monocle", but some layout changes do not show this information in the terminal.

### Briefly explain its use-case

1. Adding this feature will help in creation of better custom scripts for users, like adding notifications for changing between layouts;

**Comment by datsfilipe** [comment]
I was wrong, it shows output for every change, just take little long at some of them.

**Comment by amtoine** [comment]
> I was wrong, it shows output for every change, just take little long at some of them. Sorry for bothering.
>
no worries :wink:
feel free if you find something that looks odd :+1:
