### ISSUE TITLE
The config doesn't get sourced

### ISSUE THREAD

**Issue by Urimu** [phenax/bsp-layout#7]
I installed the AUR package and `layoutrc`, doesn't get sourced. Windows always split 50/50.

*I have now tried to install it with the install script provided in the readme. Loged out of bspwm and back in, same result.

**Comment by phenax** [comment]
Can you check if your system has `bc` installed? It is a dependency to the script. I should've mentioned it in the README.

**Comment by phenax** [comment]
@Urimu, turns out it was something else. I fixed the issue in master. Can you install it again with the install script?

**Comment by phenax** [comment]
I'm closing this issue. Feel free to re-open it if the fix doesn't work

**Comment by Urimu** [comment]
@phenax That was quick! It's working now. Thank you!
