### ISSUE TITLE
Master shrinks right down to minimum size after applying tall layout to desktop

### ISSUE THREAD

**Issue by itmecho** [phenax/bsp-layout#8]
I have the following in my `bspwmrc` to set the tall layout on my terminal desktop. For some reason, whenever I get a notification pop up or something like `pinentry` for `gpg-agent`, the master node's width shrinks right down. Maybe there's a setting I'm missing for floating windows that's interfering?

```
bsp-layout set tall 2
```

**Comment by useredsa** [comment]
> I have the following in my `bspwmrc` to set the tall layout on my terminal desktop. For some reason, whenever I get a notification pop up or something like `pinentry` for `gpg-agent`, the master node's width shrinks right down. Maybe there's a setting I'm missing for floating windows that's interfering?
> 
> ```
> bsp-layout set tall 2
> ```

In my case, I realized I had this problem because I forgot to install `bc`.

**Comment by itmecho** [comment]
Oh nice, I think that's fixed it! Should've read the README properly...
